import type { ColumnKind, ColumnMeta, TableMeta } from "./types.js";

type ColumnConfig = Partial<Omit<ColumnMeta, "name" | "label" | "sqlType" | "kind">> & {
  importHeader?: string;
  kind?: ColumnKind;
  label?: string;
  sqlType?: string;
};

function labelize(name: string) {
  return name
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function column(name: string, config: ColumnConfig = {}): ColumnMeta {
  return {
    name,
    label: config.label ?? labelize(name),
    sqlType: config.sqlType ?? "text",
    kind: config.kind ?? "text",
    importBehavior: config.importBehavior,
    importHeader: config.importHeader,
    nullable: config.nullable ?? false,
    hasDefault: config.hasDefault ?? false,
    autoGenerated: config.autoGenerated ?? false,
    isPrimaryKey: config.isPrimaryKey ?? false,
    readOnly: config.readOnly ?? false,
    hidden: config.hidden ?? false,
    searchable: config.searchable ?? false,
    foreignKey: config.foreignKey
  };
}

const timestamps = [
  column("created_at", {
    kind: "timestamp",
    sqlType: "timestamp with time zone",
    hasDefault: true,
    readOnly: true
  }),
  column("updated_at", {
    kind: "timestamp",
    sqlType: "timestamp with time zone",
    hasDefault: true,
    readOnly: true
  })
];

const prefixedPrimaryKey = column("id", {
  kind: "text",
  sqlType: "text",
  hasDefault: true,
  autoGenerated: true,
  isPrimaryKey: true,
  readOnly: true,
  hidden: true,
  searchable: true
});

// Static metadata generated from the live Supabase public schema inspected on 2026-05-14.
// Security/system tables are intentionally excluded from the app surface.
export const schemaTables: TableMeta[] = [
  {
    name: "companies",
    label: "Companies",
    primaryKeys: ["id"],
    importMatchers: [["name"]],
    displayColumn: "name",
    searchableColumns: ["name", "website", "contact_email"],
    listColumns: ["name", "website", "contact_email"],
    columns: [
      prefixedPrimaryKey,
      column("name", { searchable: true }),
      column("website", { nullable: true, searchable: true }),
      column("contact_email", {
        label: "Contact Email",
        nullable: true,
        searchable: true,
        importBehavior: "merge_email_list"
      }),
      ...timestamps
    ]
  },
  {
    name: "facilities",
    label: "Facilities",
    description:
      "Manage facilities, availability, capacity, and linked products, chemistries, and accreditations.",
    primaryKeys: ["id"],
    importMatchers: [["company_id", "name"]],
    displayColumn: "name",
    searchableColumns: ["company_id", "name", "address", "region_id"],
    listColumns: [
      "name",
      "company_id",
      "address",
      "region_id",
      "capacity_kl",
      "latitude",
      "longitude",
      "is_active"
    ],
    columns: [
      prefixedPrimaryKey,
      column("company_id", {
        label: "Company",
        importHeader: "company_name",
        kind: "text",
        sqlType: "text",
        searchable: true,
        foreignKey: { column: "company_id", referencesTable: "companies", referencesColumn: "id" }
      }),
      column("name", { searchable: true }),
      column("address", { nullable: true, searchable: true }),
      column("region_id", {
        label: "Region",
        importHeader: "region_name",
        kind: "text",
        sqlType: "text",
        nullable: true,
        searchable: true,
        foreignKey: { column: "region_id", referencesTable: "regions", referencesColumn: "id" }
      }),
      column("latitude", { kind: "number", sqlType: "double precision", nullable: true }),
      column("longitude", { kind: "number", sqlType: "double precision", nullable: true }),
      column("location", {
        kind: "custom",
        sqlType: "public.geometry(Point,4326)",
        nullable: true,
        hidden: true
      }),
      column("is_active", { label: "Active", kind: "boolean", sqlType: "boolean", hasDefault: true }),
      column("capacity_kl", {
        label: "Capacity KL",
        kind: "number",
        sqlType: "numeric",
        nullable: true
      }),
      ...timestamps,
      column("deleted_at", {
        kind: "timestamp",
        sqlType: "timestamp with time zone",
        nullable: true,
        hidden: true
      })
    ]
  },
  {
    name: "products",
    label: "Products",
    primaryKeys: ["id"],
    importMatchers: [["product_name", "cas_number"], ["cas_number"], ["product_name"]],
    displayColumn: "product_name",
    searchableColumns: ["id", "product_name", "cas_number"],
    listColumns: ["product_name", "cas_number", "category"],
    columns: [
      column("id", {
        kind: "text",
        sqlType: "text",
        isPrimaryKey: true,
        searchable: true,
        hasDefault: true,
        autoGenerated: true,
        readOnly: true,
        hidden: true
      }),
      column("product_name", { label: "Product Name", nullable: true, searchable: true }),
      column("cas_number", { label: "CAS Number", nullable: true, searchable: true }),
      column("category", {
        kind: "custom",
        sqlType: "public.product_category",
        nullable: true
      }),
      ...timestamps,
      column("deleted_at", {
        kind: "timestamp",
        sqlType: "timestamp with time zone",
        nullable: true,
        hidden: true
      })
    ]
  },
  {
    name: "regions",
    label: "Regions",
    primaryKeys: ["id"],
    importMatchers: [["iso_code"], ["name", "country"]],
    displayColumn: "name",
    searchableColumns: ["iso_code", "name", "country"],
    listColumns: ["name", "iso_code", "country"],
    columns: [
      prefixedPrimaryKey,
      column("iso_code", { label: "ISO Code", nullable: true, searchable: true }),
      column("name", { searchable: true }),
      column("country", { hasDefault: true, searchable: true }),
      ...timestamps
    ]
  },
  {
    name: "chemistries",
    label: "Chemistries",
    primaryKeys: ["id"],
    importMatchers: [["slug"]],
    displayColumn: "label",
    searchableColumns: ["slug", "label"],
    listColumns: ["label", "slug"],
    columns: [
      prefixedPrimaryKey,
      column("slug", { searchable: true }),
      column("label", { searchable: true }),
      ...timestamps
    ]
  },
  {
    name: "accreditations",
    label: "Accreditations",
    primaryKeys: ["id"],
    importMatchers: [["code"]],
    displayColumn: "label",
    searchableColumns: ["code", "label"],
    listColumns: ["label", "code"],
    columns: [
      prefixedPrimaryKey,
      column("code", { searchable: true }),
      column("label", { searchable: true }),
      ...timestamps
    ]
  },
  {
    name: "controlled_substances",
    label: "Controlled Substances",
    description: "Authoritative CAS controls used to protect enquiry dispatches.",
    primaryKeys: ["id"],
    importMatchers: [["cas_number"]],
    displayColumn: "cas_number",
    searchableColumns: ["cas_number", "reason", "scomet_entry"],
    listColumns: ["cas_number", "reason", "scomet_entry", "is_active"],
    columns: [
      column("id", {
        kind: "uuid",
        sqlType: "uuid",
        hasDefault: true,
        autoGenerated: true,
        isPrimaryKey: true,
        readOnly: true,
        hidden: true
      }),
      column("cas_number", { label: "CAS Number", searchable: true }),
      column("normalized_cas", {
        label: "Normalized CAS",
        readOnly: true,
        hidden: true
      }),
      column("reason", { nullable: true, searchable: true }),
      column("scomet_entry", { label: "SCOMET Entry", nullable: true, searchable: true }),
      column("is_active", { label: "Active", kind: "boolean", sqlType: "boolean", hasDefault: true }),
      ...timestamps
    ]
  },
  {
    name: "products_dedupe_audit",
    label: "Products Dedupe Audit",
    description: "Read-only audit trail for product deduplication events.",
    readOnly: true,
    primaryKeys: ["id"],
    displayColumn: "reason",
    searchableColumns: ["keep_id", "dup_id", "reason"],
    listColumns: ["deduped_at", "keep_id", "dup_id", "reason"],
    columns: [
      column("id", {
        kind: "number",
        sqlType: "bigint",
        autoGenerated: true,
        isPrimaryKey: true,
        readOnly: true,
        hidden: true
      }),
      column("deduped_at", {
        kind: "timestamp",
        sqlType: "timestamp with time zone",
        hasDefault: true,
        readOnly: true
      }),
      column("keep_id", { label: "Keep Product", readOnly: true, searchable: true }),
      column("dup_id", { label: "Duplicate Product", readOnly: true, searchable: true }),
      column("reason", { readOnly: true, searchable: true }),
      column("keep_before", { kind: "custom", sqlType: "jsonb", nullable: true, readOnly: true }),
      column("dup_before", { kind: "custom", sqlType: "jsonb", nullable: true, readOnly: true })
    ]
  },
  {
    name: "facility_accreditations",
    label: "Facility Accreditations",
    primaryKeys: ["facility_id", "accreditation_id"],
    importMatchers: [["facility_id", "accreditation_id"]],
    displayColumn: "awarding_body",
    searchableColumns: ["facility_id", "accreditation_id", "awarding_body", "certificate_number"],
    listColumns: [
      "awarding_body",
      "facility_id",
      "accreditation_id",
      "certificate_number",
      "awarded_at",
      "expires_at"
    ],
    columns: [
      column("facility_id", {
        label: "Facility",
        importHeader: "facility_name",
        kind: "text",
        sqlType: "text",
        isPrimaryKey: true,
        searchable: true,
        foreignKey: { column: "facility_id", referencesTable: "facilities", referencesColumn: "id" }
      }),
      column("accreditation_id", {
        label: "Accreditation",
        importHeader: "accreditation",
        kind: "text",
        sqlType: "text",
        isPrimaryKey: true,
        searchable: true,
        foreignKey: { column: "accreditation_id", referencesTable: "accreditations", referencesColumn: "id" }
      }),
      column("awarding_body", { label: "Awarding Body", nullable: true, searchable: true }),
      column("certificate_number", { label: "Certificate Number", nullable: true, searchable: true }),
      column("awarded_at", { label: "Awarded At", kind: "date", sqlType: "date", nullable: true }),
      column("expires_at", { label: "Expires At", kind: "date", sqlType: "date", nullable: true }),
      column("created_at", {
        kind: "timestamp",
        sqlType: "timestamp with time zone",
        hasDefault: true,
        readOnly: true
      })
    ]
  },
  {
    name: "facility_chemistries",
    label: "Facility Chemistries",
    primaryKeys: ["facility_id", "chemistry_id"],
    importMatchers: [["facility_id", "chemistry_id"]],
    displayColumn: "facility_id",
    searchableColumns: ["facility_id", "chemistry_id"],
    listColumns: ["facility_id", "chemistry_id"],
    columns: [
      column("facility_id", {
        label: "Facility",
        importHeader: "facility_name",
        kind: "text",
        sqlType: "text",
        isPrimaryKey: true,
        searchable: true,
        foreignKey: { column: "facility_id", referencesTable: "facilities", referencesColumn: "id" }
      }),
      column("chemistry_id", {
        label: "Chemistry",
        importHeader: "chemistry",
        kind: "text",
        sqlType: "text",
        isPrimaryKey: true,
        searchable: true,
        foreignKey: { column: "chemistry_id", referencesTable: "chemistries", referencesColumn: "id" }
      }),
      column("created_at", {
        kind: "timestamp",
        sqlType: "timestamp with time zone",
        hasDefault: true,
        readOnly: true
      })
    ]
  },
  {
    name: "facility_products",
    label: "Facility Products",
    primaryKeys: ["facility_id", "product_id"],
    importMatchers: [["facility_id", "product_id"]],
    displayColumn: "facility_id",
    searchableColumns: ["facility_id", "product_id"],
    listColumns: ["facility_id", "product_id", "is_primary"],
    columns: [
      column("facility_id", {
        label: "Facility",
        importHeader: "facility_name",
        kind: "text",
        sqlType: "text",
        isPrimaryKey: true,
        searchable: true,
        foreignKey: { column: "facility_id", referencesTable: "facilities", referencesColumn: "id" }
      }),
      column("product_id", {
        label: "Product",
        importHeader: "product",
        isPrimaryKey: true,
        searchable: true,
        foreignKey: { column: "product_id", referencesTable: "products", referencesColumn: "id" }
      }),
      column("is_primary", { label: "Primary", kind: "boolean", sqlType: "boolean", hasDefault: true }),
      column("created_at", {
        kind: "timestamp",
        sqlType: "timestamp with time zone",
        hasDefault: true,
        readOnly: true
      })
    ]
  }
];
