export type ColumnKind = "text" | "uuid" | "number" | "boolean" | "date" | "timestamp" | "custom";

export interface ForeignKeyMeta {
  column: string;
  referencesTable: string;
  referencesColumn: string;
}

export interface ColumnMeta {
  name: string;
  label: string;
  importHeader?: string;
  sqlType: string;
  kind: ColumnKind;
  importBehavior?: "replace" | "merge_email_list";
  nullable: boolean;
  hasDefault: boolean;
  autoGenerated: boolean;
  isPrimaryKey: boolean;
  readOnly: boolean;
  hidden: boolean;
  searchable: boolean;
  foreignKey?: ForeignKeyMeta;
}

export interface TableMeta {
  name: string;
  label: string;
  description?: string;
  readOnly?: boolean;
  primaryKeys: string[];
  importMatchers?: string[][];
  displayColumn: string;
  searchableColumns: string[];
  listColumns: string[];
  columns: ColumnMeta[];
}

export interface SchemaResponse {
  tables: TableMeta[];
}

export interface RecordsResponse {
  records: Record<string, unknown>[];
  total: number;
}

export interface ImportResponse {
  processed: number;
  created: number;
  updated: number;
}

export interface OptionsResponse {
  options: Array<{
    value: string;
    label: string;
    meta?: Record<string, string | null>;
  }>;
}

export type OptionRecord = OptionsResponse["options"][number];

export interface FacilityChemistryRelation {
  chemistryId: string;
}

export interface FacilityProductRelation {
  productId: string;
  isPrimary: boolean;
}

export interface FacilityAccreditationRelation {
  accreditationId: string;
  awardingBody: string | null;
  certificateNumber: string | null;
  awardedAt: string | null;
  expiresAt: string | null;
}

export interface FacilityRelationsResponse {
  facilityId: string;
  chemistries: FacilityChemistryRelation[];
  products: FacilityProductRelation[];
  accreditations: FacilityAccreditationRelation[];
}

export interface FacilityRelationsUpsertRequest {
  chemistries?: FacilityChemistryRelation[];
  products?: FacilityProductRelation[];
  accreditations?: Array<{
    accreditationId: string;
    awardingBody?: string | null;
    certificateNumber?: string | null;
    awardedAt?: string | null;
    expiresAt?: string | null;
  }>;
}

export interface AdminUser {
  id: string;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  imageUrl: string | null;
  role: "admin";
}

export interface AdminMeResponse {
  user: AdminUser;
}

// API requests use camelCase DTOs. Some list/detail responses intentionally
// return database-shaped rows while the UI is migrated feature by feature.
export type ApiRecord = Record<string, any>;

export interface ListResponse<T = ApiRecord> {
  records: T[];
  total: number;
}

export interface DashboardMetricsResponse {
  summary?: Record<string, number>;
  monthly?: ApiRecord[];
  topProducts?: ApiRecord[];
}

export interface EnquiryDraftQuantity {
  quantity: number;
  unit: string;
}

export interface EnquiryDraftItemInput {
  productId: string | null;
  productName: string | null;
  casNumber: string | null;
  remarks: string | null;
  quantities: EnquiryDraftQuantity[];
}

export interface EnquiryInput {
  customerName: string;
  customerEmail?: string | null;
  customerCompany?: string | null;
  externalReference?: string | null;
  enquiryType?: string | null;
  receivedAt: string;
  notes?: string | null;
  items: EnquiryDraftItemInput[];
}

export interface EnquiryImportRow {
  externalReference?: unknown;
  customerName?: unknown;
  customerEmail?: unknown;
  customerCompany?: unknown;
  enquiryType?: unknown;
  receivedAt?: unknown;
  productName?: unknown;
  casNumber?: unknown;
  quantity?: unknown;
  unit?: unknown;
  remarks?: unknown;
}

export interface EnquiryImportResponse {
  created: number;
}

export interface ProductSearchResponse {
  records: ApiRecord[];
}

export interface VendorCandidatesResponse {
  records: ApiRecord[];
}

export interface DispatchSendResponse {
  sent: number;
  failed: number;
}
