export type ColumnKind =
  | "text"
  | "uuid"
  | "number"
  | "boolean"
  | "date"
  | "timestamp"
  | "custom";

export interface ForeignKeyMeta {
  column: string;
  referencesTable: string;
  referencesColumn: string;
}

export interface ColumnMeta {
  name: string;
  label: string;
  sqlType: string;
  kind: ColumnKind;
  nullable: boolean;
  hasDefault: boolean;
  autoGenerated: boolean;
  isPrimaryKey: boolean;
  readOnly: boolean;
  hidden: boolean;
  searchable: boolean;
  foreignKey?: ForeignKeyMeta;
}

export interface TableMeta {
  name: string;
  label: string;
  description?: string;
  primaryKeys: string[];
  importMatchers?: string[][];
  displayColumn: string;
  searchableColumns: string[];
  listColumns: string[];
  columns: ColumnMeta[];
  specialHandler?: "users";
}

export interface SchemaResponse {
  tables: TableMeta[];
}

export interface RecordsResponse {
  records: Record<string, unknown>[];
  total: number;
}

export interface ImportResponse {
  processed: number;
  created: number;
  updated: number;
}

export interface OptionsResponse {
  options: Array<{
    value: string;
    label: string;
  }>;
}

export interface FacilityRelationsResponse {
  facilityId: string;
  chemistryIds: string[];
  productIds: string[];
  accreditations: Array<{
    accreditationId: string;
    awardingBody: string | null;
    certificateNumber: string | null;
    awardedAt: string | null;
    expiresAt: string | null;
  }>;
}

export interface FacilityRelationsUpsertRequest {
  chemistryIds?: string[];
  productIds?: string[];
  accreditations?: Array<{
    accreditationId: string;
    awardingBody?: string | null;
    certificateNumber?: string | null;
    awardedAt?: string | null;
    expiresAt?: string | null;
  }>;
}

export interface AuthorizedUser {
  id: string;
  email: string | null;
  fullName: string | null;
  role: string;
}

export interface AuthStatusResponse {
  user: AuthorizedUser;
}
