import { startTransition, useDeferredValue, useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import type {
  ColumnMeta,
  FacilityRelationsResponse,
  FacilityRelationsUpsertRequest,
  OptionsResponse,
  RecordsResponse,
  SchemaResponse,
  TableMeta,
  AuthorizedUser
} from "../shared/types";

type RowRecord = Record<string, unknown>;
type FormState = Record<string, string>;
type LookupCache = Record<string, OptionsResponse["options"]>;

interface EditorState {
  mode: "create" | "edit";
  row: RowRecord | null;
}

interface ImportState {
  fileName: string;
  rows: RowRecord[];
}

const PAGE_SIZE = 25;

interface AdminConsoleProps {
  accessToken: string;
  currentUser: AuthorizedUser;
  onSignOut: () => Promise<void> | void;
}

export default function AdminConsole({ accessToken, currentUser, onSignOut }: AdminConsoleProps) {
  const [tables, setTables] = useState<TableMeta[]>([]);
  const [selectedTableName, setSelectedTableName] = useState<string>("");
  const [records, setRecords] = useState<RowRecord[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(0);
  const [search, setSearch] = useState("");
  const deferredSearch = useDeferredValue(search);
  const [loadingSchema, setLoadingSchema] = useState(true);
  const [loadingRecords, setLoadingRecords] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>("");
  const [notice, setNotice] = useState<string>("");
  const [editor, setEditor] = useState<EditorState | null>(null);
  const [formState, setFormState] = useState<FormState>({});
  const [importState, setImportState] = useState<ImportState | null>(null);
  const [lookups, setLookups] = useState<LookupCache>({});
  const [facilityRelations, setFacilityRelations] = useState<FacilityRelationsResponse | null>(null);
  const [facilityRelationsDraft, setFacilityRelationsDraft] = useState<FacilityRelationsUpsertRequest | null>(null);
  const [facilityRelationsLoading, setFacilityRelationsLoading] = useState(false);

  const selectedTable = useMemo(
    () => tables.find((table) => table.name === selectedTableName) ?? null,
    [selectedTableName, tables]
  );
  const foreignTableNames = useMemo(() => {
    if (!selectedTable) {
      return [];
    }

    return [...new Set(selectedTable.columns.flatMap((column) => column.foreignKey?.referencesTable ?? []))];
  }, [selectedTable]);

  useEffect(() => {
    void loadSchema();
  }, []);

  useEffect(() => {
    if (!selectedTable) {
      return;
    }

    const controller = new AbortController();
    setLoadingRecords(true);
    setError("");

    void api<RecordsResponse>(accessToken,
      `/api/records/${selectedTable.name}?limit=${PAGE_SIZE}&offset=${page * PAGE_SIZE}&search=${encodeURIComponent(
        deferredSearch
      )}`,
      { signal: controller.signal }
    )
      .then((data) => {
        setRecords(data.records);
        setTotal(data.total);
      })
      .catch((apiError: unknown) => {
        if (!controller.signal.aborted) {
          setError(getErrorMessage(apiError));
        }
      })
      .finally(() => {
        if (!controller.signal.aborted) {
          setLoadingRecords(false);
        }
      });

    return () => controller.abort();
  }, [deferredSearch, page, selectedTable]);

  useEffect(() => {
    if (!selectedTable || foreignTableNames.length === 0) {
      return;
    }

    for (const foreignTable of foreignTableNames) {
      if (lookups[foreignTable]) {
        continue;
      }

      void api<OptionsResponse>(accessToken, `/api/options/${foreignTable}`)
        .then((data) => {
          setLookups((current) => ({ ...current, [foreignTable]: data.options }));
        })
        .catch((apiError: unknown) => {
          setError(getErrorMessage(apiError));
        });
    }
  }, [foreignTableNames, lookups, selectedTable]);

  const visibleColumns = useMemo(() => {
    if (!selectedTable) {
      return [];
    }

    return selectedTable.listColumns
      .map((columnName) => selectedTable.columns.find((column) => column.name === columnName))
      .filter((column): column is ColumnMeta => Boolean(column));
  }, [selectedTable]);

  const editableColumns = useMemo(() => {
    if (!selectedTable) {
      return [];
    }

    return selectedTable.columns.filter((column) => !column.readOnly && !column.hidden);
  }, [selectedTable]);
  const editableFieldCount = editableColumns.filter((column) => !column.autoGenerated).length;
  const selectedTableDetails = useMemo(() => {
    if (!selectedTable) {
      return {
        autoManagedFields: [],
        connectedTableCount: 0,
        ignoredImportHeaders: [],
        importableColumns: []
      };
    }

    const autoManagedColumns = selectedTable.columns.filter((column) => column.autoGenerated || column.readOnly);
    const ignoredColumns = selectedTable.columns.filter(
      (column) => column.autoGenerated || column.hidden || column.readOnly
    );
    const importableTableColumns = selectedTable.columns.filter(
      (column) => !column.autoGenerated && !column.hidden && !column.readOnly
    );

    return {
      autoManagedFields: autoManagedColumns.map((column) => column.label),
      connectedTableCount: selectedTable.columns.filter((column) => column.foreignKey).length,
      ignoredImportHeaders: ignoredColumns.map((column) => column.name),
      importableColumns: importableTableColumns
    };
  }, [selectedTable]);
  const { autoManagedFields, connectedTableCount, ignoredImportHeaders, importableColumns } = selectedTableDetails;
  const importHeaders = useMemo(
    () => ({
      optional: importableColumns.filter((column) => column.nullable || column.hasDefault).map((column) => column.name),
      required: importableColumns.filter((column) => !column.nullable && !column.hasDefault).map((column) => column.name)
    }),
    [importableColumns]
  );
  const { optional: optionalImportHeaders, required: requiredImportHeaders } = importHeaders;
  const previewColumns = useMemo(() => {
    if (!selectedTable || !importState?.rows.length) {
      return [];
    }

    const hiddenHeaders = new Set(
      selectedTable.columns
        .filter((column) => column.autoGenerated || column.hidden || column.readOnly)
        .map((column) => column.name)
    );

    return Object.keys(importState.rows[0]).filter((column) => !hiddenHeaders.has(column));
  }, [importState?.rows, selectedTable]);

  async function loadSchema() {
    try {
      setLoadingSchema(true);
      const data = await api<SchemaResponse>(accessToken, "/api/schema");
      setTables(data.tables);
      if (data.tables.length > 0) {
        setSelectedTableName(data.tables[0].name);
      }
    } catch (apiError) {
      setError(getErrorMessage(apiError));
    } finally {
      setLoadingSchema(false);
    }
  }

  function openCreateEditor() {
    if (!selectedTable) {
      return;
    }

    setNotice("");
    setEditor({ mode: "create", row: null });
    setFormState(createEmptyForm(selectedTable));
    setFacilityRelations(null);
    setFacilityRelationsDraft(null);
  }

  function openEditEditor(row: RowRecord) {
    if (!selectedTable) {
      return;
    }

    setNotice("");
    setEditor({ mode: "edit", row });
    setFormState(createFormFromRow(selectedTable, row));

    if (selectedTable.name === "facilities") {
      const facilityId = String(row.id ?? "");
      if (facilityId) {
        void loadFacilityRelations(facilityId);
      }
    } else {
      setFacilityRelations(null);
      setFacilityRelationsDraft(null);
    }
  }

  function closePanels() {
    setEditor(null);
    setImportState(null);
    setFormState({});
    setFacilityRelations(null);
    setFacilityRelationsDraft(null);
  }

  async function handleSaveRecord(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!selectedTable || !editor) {
      return;
    }

    try {
      setBusy(true);
      setError("");
      if (
        selectedTable.name === "facilities" &&
        editor.mode === "edit" &&
        facilityRelationsDraft?.accreditations
      ) {
        const invalid = facilityRelationsDraft.accreditations.some((row) => !row.accreditationId);
        if (invalid) {
          throw new Error("Each accreditation row must select an accreditation.");
        }
      }
      const payload = buildPayload(selectedTable, formState, editor);
      const method = editor.mode === "create" ? "POST" : "PATCH";
      await api(accessToken, `/api/records/${selectedTable.name}`, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });

      if (
        selectedTable.name === "facilities" &&
        editor.mode === "edit" &&
        facilityRelationsDraft &&
        editor.row &&
        String(editor.row.id ?? "")
      ) {
        const facilityId = String(editor.row.id ?? "");
        await api<FacilityRelationsResponse>(accessToken, `/api/facilities/${facilityId}/relations`, {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(facilityRelationsDraft)
        });
      }

      setNotice(
        editor.mode === "create"
          ? `${selectedTable.label} row created.`
          : `${selectedTable.label} row updated.`
      );
      closePanels();
      await refreshRecords();
    } catch (apiError) {
      setError(getErrorMessage(apiError));
    } finally {
      setBusy(false);
    }
  }

  async function loadFacilityRelations(facilityId: string) {
    try {
      setFacilityRelationsLoading(true);
      setError("");

      // Ensure options exist for relation pickers.
      const needed = ["chemistries", "products", "accreditations"];
      await Promise.all(
        needed
          .filter((tableName) => !lookups[tableName])
          .map(async (tableName) => {
            const data = await api<OptionsResponse>(accessToken, `/api/options/${tableName}`);
            setLookups((current) => ({ ...current, [tableName]: data.options }));
          })
      );

      const data = await api<FacilityRelationsResponse>(accessToken, `/api/facilities/${facilityId}/relations`);
      setFacilityRelations(data);
      setFacilityRelationsDraft({
        chemistryIds: data.chemistryIds,
        productIds: data.productIds,
        accreditations: data.accreditations.map((row) => ({
          accreditationId: row.accreditationId,
          awardingBody: row.awardingBody,
          certificateNumber: row.certificateNumber,
          awardedAt: row.awardedAt,
          expiresAt: row.expiresAt
        }))
      });
    } catch (apiError: unknown) {
      setError(getErrorMessage(apiError));
    } finally {
      setFacilityRelationsLoading(false);
    }
  }

  async function handleDeleteRecord(row: RowRecord) {
    if (!selectedTable) {
      return;
    }

    const identifier = getRowTitle(selectedTable, row, lookups);

    if (!window.confirm(`Delete this row?\n${identifier}`)) {
      return;
    }

    try {
      setBusy(true);
      setError("");
      await api(accessToken, `/api/records/${selectedTable.name}`, {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(row)
      });

      setNotice(`${selectedTable.label} row deleted.`);
      await refreshRecords();
    } catch (apiError) {
      setError(getErrorMessage(apiError));
    } finally {
      setBusy(false);
    }
  }

  async function refreshRecords() {
    if (!selectedTable) {
      return;
    }

    const data = await api<RecordsResponse>(
      accessToken,
      `/api/records/${selectedTable.name}?limit=${PAGE_SIZE}&offset=${page * PAGE_SIZE}&search=${encodeURIComponent(
        deferredSearch
      )}`
    );
    setRecords(data.records);
    setTotal(data.total);
  }

  async function handleRefreshClick() {
    if (!selectedTable || loadingRecords || refreshing) {
      return;
    }

    try {
      setRefreshing(true);
      setError("");
      await refreshRecords();
    } catch (apiError) {
      setError(getErrorMessage(apiError));
    } finally {
      setRefreshing(false);
    }
  }

  async function handleImportSubmit() {
    if (!selectedTable || !importState) {
      return;
    }

    try {
      setBusy(true);
      setError("");
      const response = await api<{ processed: number }>(accessToken, `/api/import/${selectedTable.name}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ rows: importState.rows })
      });

      setNotice(`Imported ${response.processed} rows into ${selectedTable.label}.`);
      closePanels();
      await refreshRecords();
    } catch (apiError) {
      setError(getErrorMessage(apiError));
    } finally {
      setBusy(false);
    }
  }

  async function handleFileSelected(file: File | null) {
    if (!file) {
      return;
    }

    try {
      const XLSX = await import("xlsx");
      const workbook = XLSX.read(await file.arrayBuffer(), {
        type: "array",
        cellDates: false
      });
      const sheetName = workbook.SheetNames[0];
      const sheet = workbook.Sheets[sheetName];
      const rows = XLSX.utils.sheet_to_json<RowRecord>(sheet, {
        defval: "",
        raw: false
      });

      setImportState({
        fileName: file.name,
        rows
      });
      setNotice("");
    } catch (parseError) {
      setError(`Could not read Excel file: ${getErrorMessage(parseError)}`);
    }
  }

  if (loadingSchema) {
    return <div className="shell loading-screen">Loading schema…</div>;
  }

  if (!selectedTable) {
    return <div className="shell loading-screen">No admin table metadata is configured.</div>;
  }

  const pageCount = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const isFacilityEditor = selectedTable.name === "facilities" && editor?.mode === "edit";

  return (
    <div className="shell">
      <aside className="sidebar">
        <div className="brand">
          <p className="eyebrow">Supabase Admin</p>
          <h1>Covenants Control Room</h1>
          <p className="sidebar-copy">
            Clean internal tooling for operating your Supabase data without exposing system keys.
          </p>
          <div className="session-card">
            <strong>{currentUser.fullName || currentUser.email || "Authorized user"}</strong>
            <span>{currentUser.email || "No email available"}</span>
            <span className="session-role">Role: {currentUser.role}</span>
            <button className="ghost-button" onClick={() => void onSignOut()} type="button">
              Sign out
            </button>
          </div>
        </div>

        <nav className="table-list">
          {tables.map((table) => (
            <button
              key={table.name}
              className={table.name === selectedTable.name ? "table-link active" : "table-link"}
              onClick={() => {
                startTransition(() => {
                  setSelectedTableName(table.name);
                  setPage(0);
                  setSearch("");
                  setNotice("");
                  setError("");
                  closePanels();
                });
              }}
              type="button"
            >
              <span>{table.label}</span>
              <strong>
                {table.columns.filter((column) => !column.hidden && !column.readOnly).length} editable
                fields
              </strong>
            </button>
          ))}
        </nav>
      </aside>

      <main className="workspace">
        <section className="hero">
          <div>
            <p className="eyebrow">Table</p>
            <h2>{selectedTable.label}</h2>
            <p className="hero-copy">
              {selectedTable.description ??
                `Manage ${selectedTable.label.toLowerCase()} with safe forms, bulk import, and auto-managed system fields.`}
            </p>
            <div className="hero-tags">
              <span className="tag">Generated IDs hidden</span>
              <span className="tag">Excel import ready</span>
              <span className="tag">Supabase-backed</span>
            </div>
          </div>

          <div className="hero-stats">
            <div className="stat-card">
              <span>Total Rows</span>
              <strong>{total}</strong>
            </div>
            <div className="stat-card">
              <span>Editable Fields</span>
              <strong>{editableFieldCount}</strong>
            </div>
            <div className="stat-card">
              <span>Connected Tables</span>
              <strong>{connectedTableCount}</strong>
            </div>
          </div>
        </section>

        <section className="panel controls">
          <div className="controls-copy">
            <label className="search">
              <span>Search rows</span>
              <input
                value={search}
                onChange={(event) => {
                  setSearch(event.target.value);
                  setPage(0);
                }}
                placeholder={`Search ${selectedTable.label.toLowerCase()}...`}
                type="search"
              />
            </label>
            <p className="helper-note">
              Auto-generated fields stay hidden. Imports ignore them even if they appear in the sheet.
            </p>
          </div>

          <div className="actions">
            <button
              className="ghost-button button-with-spinner"
              disabled={loadingRecords || refreshing}
              onClick={() => void handleRefreshClick()}
              type="button"
            >
              {refreshing ? <span aria-hidden="true" className="spin" /> : null}
              {refreshing ? "Refreshing…" : "Refresh"}
            </button>
            <button className="ghost-button" onClick={() => setImportState({ fileName: "", rows: [] })} type="button">
              Import Excel
            </button>
            <button className="primary-button" onClick={openCreateEditor} type="button">
              Add Row
            </button>
          </div>
        </section>

        {error ? <p className="banner error">{error}</p> : null}
        {notice ? <p className="banner success">{notice}</p> : null}

        <section className="panel table-panel">
          <div className="table-meta">
            <span>
              Page {page + 1} of {pageCount}
            </span>
            <span>{loadingRecords ? "Loading rows…" : `${records.length} rows loaded`}</span>
          </div>

          <div className="table-scroller">
            <table>
              <thead>
                <tr>
                  {visibleColumns.map((column) => (
                    <th key={column.name}>{column.label}</th>
                  ))}
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {records.length === 0 ? (
                  <tr>
                    <td colSpan={visibleColumns.length + 1}>
                      <div className="empty-state">No rows matched the current query.</div>
                    </td>
                  </tr>
                ) : (
                  records.map((row, index) => (
                    <tr key={createRowKey(selectedTable, row, index)}>
                      {visibleColumns.map((column) => (
                        <td key={column.name}>
                          {formatColumnValue(column, row[column.name], lookups)}
                        </td>
                      ))}
                      <td>
                        <div className="row-actions">
                          <button onClick={() => openEditEditor(row)} type="button">
                            Edit
                          </button>
                          <button
                            className="danger-link"
                            onClick={() => void handleDeleteRecord(row)}
                            type="button"
                          >
                            Delete
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          <div className="pagination">
            <button disabled={page === 0 || loadingRecords} onClick={() => setPage((value) => value - 1)} type="button">
              Previous
            </button>
            <button
              disabled={page + 1 >= pageCount || loadingRecords}
              onClick={() => setPage((value) => value + 1)}
              type="button"
            >
              Next
            </button>
          </div>
        </section>
      </main>

      {editor ? (
        <div className="overlay">
          <section className="dialog">
            <div className="dialog-head">
              <div>
                <p className="eyebrow">{editor.mode === "create" ? "Create" : "Edit"}</p>
                <h3>{selectedTable.label} Row</h3>
                <p className="dialog-copy">
                  System-managed fields like generated IDs and timestamps stay hidden automatically.
                </p>
              </div>
              <button className="close-button" onClick={closePanels} type="button">
                Close
              </button>
            </div>

            <form className="record-form" onSubmit={(event) => void handleSaveRecord(event)}>
              <div className="form-grid">
              {editableColumns.map((column) => {
                const disabled = editor.mode === "edit" && column.isPrimaryKey;
                const foreignOptions = column.foreignKey
                  ? lookups[column.foreignKey.referencesTable] ?? []
                  : [];

                return (
                  <label className="field" key={column.name}>
                      <span>
                        {column.label}
                        {column.nullable ? " optional" : ""}
                      </span>

                    {column.foreignKey ? (
                      <select
                        disabled={disabled}
                        value={formState[column.name] ?? ""}
                        onChange={(event) =>
                          setFormState((current) => ({
                            ...current,
                            [column.name]: event.target.value
                          }))
                        }
                      >
                        <option value="">Select {column.label}</option>
                        {foreignOptions.map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    ) : (
                      renderFieldInput(column, formState[column.name] ?? "", disabled, (value) =>
                        setFormState((current) => ({
                          ...current,
                          [column.name]: value
                        }))
                      )
                    )}
                  </label>
                );
              })}
              </div>

              {isFacilityEditor ? (
                <div className="auto-managed-note">
                  <strong>Facility relations</strong>
                  <div style={{ marginTop: 12, display: "grid", gap: 12 }}>
                    <label className="field">
                      <span>Chemistries</span>
                      <select
                        multiple
                        disabled={busy || facilityRelationsLoading}
                        value={facilityRelationsDraft?.chemistryIds ?? []}
                        onChange={(event) => {
                          const values = Array.from(event.target.selectedOptions).map((opt) => opt.value);
                          setFacilityRelationsDraft((current) => ({
                            ...(current ?? {}),
                            chemistryIds: values
                          }));
                        }}
                      >
                        {(lookups.chemistries ?? []).map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </label>

                    <label className="field">
                      <span>Products</span>
                      <select
                        multiple
                        disabled={busy || facilityRelationsLoading}
                        value={facilityRelationsDraft?.productIds ?? []}
                        onChange={(event) => {
                          const values = Array.from(event.target.selectedOptions).map((opt) => opt.value);
                          setFacilityRelationsDraft((current) => ({
                            ...(current ?? {}),
                            productIds: values
                          }));
                        }}
                      >
                        {(lookups.products ?? []).map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </label>

                    <div className="panel" style={{ padding: 12 }}>
                      <div style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "center" }}>
                        <strong>Accreditations</strong>
                        <button
                          className="ghost-button"
                          type="button"
                          disabled={busy || facilityRelationsLoading}
                          onClick={() =>
                            setFacilityRelationsDraft((current) => ({
                              ...(current ?? {}),
                              accreditations: [
                                ...((current?.accreditations ?? []) as NonNullable<
                                  FacilityRelationsUpsertRequest["accreditations"]
                                >),
                                {
                                  accreditationId: "",
                                  awardingBody: null,
                                  certificateNumber: null,
                                  awardedAt: null,
                                  expiresAt: null
                                }
                              ]
                            }))
                          }
                        >
                          Add accreditation
                        </button>
                      </div>

                      {facilityRelationsLoading && !facilityRelations ? (
                        <p className="helper-note" style={{ marginTop: 8 }}>
                          Loading facility relations…
                        </p>
                      ) : null}

                      {(facilityRelationsDraft?.accreditations ?? []).length === 0 ? (
                        <p className="helper-note" style={{ marginTop: 8 }}>
                          No accreditations yet.
                        </p>
                      ) : (
                        <div style={{ marginTop: 12, display: "grid", gap: 10 }}>
                          {(facilityRelationsDraft?.accreditations ?? []).map((row, index) => (
                            <div
                              key={`accr-${index}`}
                              style={{
                                display: "grid",
                                gridTemplateColumns: "2fr 1fr 1fr 1fr 1fr auto",
                                gap: 8,
                                alignItems: "end"
                              }}
                            >
                              <label className="field" style={{ margin: 0 }}>
                                <span>Accreditation</span>
                                <select
                                  disabled={busy || facilityRelationsLoading}
                                  value={row.accreditationId}
                                  onChange={(event) => {
                                    const accreditationId = event.target.value;
                                    setFacilityRelationsDraft((current) => ({
                                      ...(current ?? {}),
                                      accreditations: (current?.accreditations ?? []).map((entry, entryIndex) =>
                                        entryIndex === index ? { ...entry, accreditationId } : entry
                                      )
                                    }));
                                  }}
                                >
                                  <option value="">Select accreditation</option>
                                  {(lookups.accreditations ?? []).map((option) => (
                                    <option key={option.value} value={option.value}>
                                      {option.label}
                                    </option>
                                  ))}
                                </select>
                              </label>

                              <label className="field" style={{ margin: 0 }}>
                                <span>Awarding body</span>
                                <input
                                  disabled={busy || facilityRelationsLoading}
                                  type="text"
                                  value={row.awardingBody ?? ""}
                                  onChange={(event) => {
                                    const awardingBody = event.target.value || null;
                                    setFacilityRelationsDraft((current) => ({
                                      ...(current ?? {}),
                                      accreditations: (current?.accreditations ?? []).map((entry, entryIndex) =>
                                        entryIndex === index ? { ...entry, awardingBody } : entry
                                      )
                                    }));
                                  }}
                                />
                              </label>

                              <label className="field" style={{ margin: 0 }}>
                                <span>Certificate #</span>
                                <input
                                  disabled={busy || facilityRelationsLoading}
                                  type="text"
                                  value={row.certificateNumber ?? ""}
                                  onChange={(event) => {
                                    const certificateNumber = event.target.value || null;
                                    setFacilityRelationsDraft((current) => ({
                                      ...(current ?? {}),
                                      accreditations: (current?.accreditations ?? []).map((entry, entryIndex) =>
                                        entryIndex === index ? { ...entry, certificateNumber } : entry
                                      )
                                    }));
                                  }}
                                />
                              </label>

                              <label className="field" style={{ margin: 0 }}>
                                <span>Awarded at</span>
                                <input
                                  disabled={busy || facilityRelationsLoading}
                                  type="date"
                                  value={row.awardedAt ?? ""}
                                  onChange={(event) => {
                                    const awardedAt = event.target.value || null;
                                    setFacilityRelationsDraft((current) => ({
                                      ...(current ?? {}),
                                      accreditations: (current?.accreditations ?? []).map((entry, entryIndex) =>
                                        entryIndex === index ? { ...entry, awardedAt } : entry
                                      )
                                    }));
                                  }}
                                />
                              </label>

                              <label className="field" style={{ margin: 0 }}>
                                <span>Expires at</span>
                                <input
                                  disabled={busy || facilityRelationsLoading}
                                  type="date"
                                  value={row.expiresAt ?? ""}
                                  onChange={(event) => {
                                    const expiresAt = event.target.value || null;
                                    setFacilityRelationsDraft((current) => ({
                                      ...(current ?? {}),
                                      accreditations: (current?.accreditations ?? []).map((entry, entryIndex) =>
                                        entryIndex === index ? { ...entry, expiresAt } : entry
                                      )
                                    }));
                                  }}
                                />
                              </label>

                              <button
                                className="danger-link"
                                type="button"
                                disabled={busy || facilityRelationsLoading}
                                onClick={() =>
                                  setFacilityRelationsDraft((current) => ({
                                    ...(current ?? {}),
                                    accreditations: (current?.accreditations ?? []).filter(
                                      (_entry, entryIndex) => entryIndex !== index
                                    )
                                  }))
                                }
                              >
                                Remove
                              </button>
                            </div>
                          ))}
                        </div>
                      )}

                      {facilityRelationsDraft?.accreditations?.some((row) => !row.accreditationId) ? (
                        <p className="helper-note" style={{ marginTop: 8 }}>
                          Tip: each accreditation row must select an accreditation before saving.
                        </p>
                      ) : null}
                    </div>
                  </div>
                </div>
              ) : null}

              {autoManagedFields.length > 0 ? (
                <div className="auto-managed-note">
                  <strong>Handled automatically:</strong> {autoManagedFields.join(", ")}
                </div>
              ) : null}

              {selectedTable.specialHandler === "users" ? (
                <label className="field">
                  <span>Password</span>
                  <input
                    placeholder={
                      editor.mode === "create"
                        ? "Optional. Leave blank for an auto-generated password."
                        : "Optional. Set to reset the user password."
                    }
                    type="password"
                    value={formState.password ?? ""}
                    onChange={(event) =>
                      setFormState((current) => ({
                        ...current,
                        password: event.target.value
                      }))
                    }
                  />
                </label>
              ) : null}

              <div className="dialog-actions">
                <button className="ghost-button" onClick={closePanels} type="button">
                  Cancel
                </button>
                <button className="primary-button" disabled={busy} type="submit">
                  {busy ? "Saving…" : editor.mode === "create" ? "Create Row" : "Save Changes"}
                </button>
              </div>
            </form>
          </section>
        </div>
      ) : null}

      {importState ? (
        <div className="overlay">
          <section className="dialog import-dialog">
            <div className="dialog-head">
              <div>
                <p className="eyebrow">Excel Import</p>
                <h3>{selectedTable.label}</h3>
                <p className="dialog-copy">
                  Match spreadsheet headers to database columns. Generated IDs and timestamps are ignored.
                </p>
              </div>
              <button className="close-button" onClick={closePanels} type="button">
                Close
              </button>
            </div>

            <label className="upload-zone">
              <input
                accept=".xlsx,.xls,.csv"
                onChange={(event) => void handleFileSelected(event.target.files?.[0] ?? null)}
                type="file"
              />
              <span>Choose an Excel file whose column headers match the table columns.</span>
            </label>

            <div className="import-summary">
              <strong>{importState.fileName || "No file selected yet"}</strong>
              <span>{importState.rows.length} parsed rows</span>
            </div>

            <div className="auto-managed-note">
              <strong>Excel headers (exact column names)</strong>
              <p className="helper-note" style={{ marginTop: 8 }}>
                Your spreadsheet column headers must match these names exactly.
              </p>
              <div style={{ marginTop: 8, display: "grid", gap: 8 }}>
                <div>
                  <strong>Required:</strong>{" "}
                  {requiredImportHeaders.length > 0
                    ? requiredImportHeaders.map((name) => (
                        <code key={`req-${name}`} style={{ marginRight: 8 }}>
                          {name}
                        </code>
                      ))
                    : "None"}
                </div>
                <div>
                  <strong>Optional:</strong>{" "}
                  {optionalImportHeaders.length > 0
                    ? optionalImportHeaders.map((name) => (
                        <code key={`opt-${name}`} style={{ marginRight: 8 }}>
                          {name}
                        </code>
                      ))
                    : "None"}
                </div>
                <div>
                  <strong>Ignored:</strong>{" "}
                  {ignoredImportHeaders.length > 0
                    ? ignoredImportHeaders.map((name) => (
                        <code key={`ign-${name}`} style={{ marginRight: 8 }}>
                          {name}
                        </code>
                      ))
                    : "None"}
                </div>
              </div>
            </div>

            {importState.rows.length > 0 ? (
              <div className="preview-table">
                <table>
                  <thead>
                    <tr>
                      {previewColumns.map((column) => (
                        <th key={column}>{column}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {importState.rows.slice(0, 5).map((row, rowIndex) => (
                      <tr key={`preview-${rowIndex}`}>
                        {previewColumns.map((column) => (
                          <td key={column}>{formatCellValue(row[column])}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : null}

            <div className="dialog-actions">
              <button className="ghost-button" onClick={closePanels} type="button">
                Cancel
              </button>
              <button
                className="primary-button"
                disabled={busy || importState.rows.length === 0}
                onClick={() => void handleImportSubmit()}
                type="button"
              >
                {busy ? "Importing…" : "Import Rows"}
              </button>
            </div>
          </section>
        </div>
      ) : null}
    </div>
  );
}

function renderFieldInput(
  column: ColumnMeta,
  value: string,
  disabled: boolean,
  onChange: (value: string) => void
) {
  if (column.kind === "boolean") {
    return (
      <select disabled={disabled} value={value} onChange={(event) => onChange(event.target.value)}>
        <option value="">Select</option>
        <option value="true">True</option>
        <option value="false">False</option>
      </select>
    );
  }

  if (column.kind === "date") {
    return (
      <input
        disabled={disabled}
        type="date"
        value={value}
        onChange={(event) => onChange(event.target.value)}
      />
    );
  }

  if (column.kind === "timestamp") {
    return (
      <input
        disabled={disabled}
        type="datetime-local"
        value={value}
        onChange={(event) => onChange(event.target.value)}
      />
    );
  }

  if (column.kind === "number") {
    return (
      <input
        disabled={disabled}
        type="number"
        value={value}
        onChange={(event) => onChange(event.target.value)}
      />
    );
  }

  return (
    <input
      disabled={disabled}
      placeholder={`Enter ${column.label.toLowerCase()}`}
      type="text"
      value={value}
      onChange={(event) => onChange(event.target.value)}
    />
  );
}

function createEmptyForm(table: TableMeta): FormState {
  return Object.fromEntries(
    table.columns
      .filter((column) => !column.readOnly && !column.hidden && !column.autoGenerated)
      .map((column) => [column.name, ""])
  );
}

function createFormFromRow(table: TableMeta, row: RowRecord): FormState {
  const entries = table.columns
    .filter((column) => !column.readOnly && !column.hidden && !column.autoGenerated)
    .map((column) => [column.name, stringifyFormValue(column, row[column.name])]);

  return Object.fromEntries(entries);
}

function stringifyFormValue(column: ColumnMeta, value: unknown): string {
  if (value === undefined || value === null) {
    return "";
  }

  if (column.kind === "timestamp") {
    return toDateTimeLocalValue(String(value));
  }

  if (column.kind === "date") {
    return String(value).slice(0, 10);
  }

  return String(value);
}

function buildPayload(table: TableMeta, formState: FormState, editor: EditorState): RowRecord {
  const payload: RowRecord = {};

  if (editor.mode === "edit" && editor.row) {
    for (const primaryKey of table.primaryKeys) {
      payload[primaryKey] = editor.row[primaryKey];
    }
  }

  for (const column of table.columns) {
    if (column.hidden || column.readOnly || column.autoGenerated) {
      continue;
    }

    const value = formState[column.name];

    if (value === undefined) {
      continue;
    }

    payload[column.name] = value;
  }

  if (table.specialHandler === "users" && formState.password?.trim()) {
    payload.password = formState.password.trim();
  }

  return payload;
}

function getRowTitle(table: TableMeta, row: RowRecord, lookups: LookupCache) {
  const displayColumn = table.columns.find((column) => column.name === table.displayColumn);

  if (displayColumn) {
    const displayValue = formatColumnValue(displayColumn, row[displayColumn.name], lookups);
    if (displayValue !== "—") {
      return displayValue;
    }
  }

  const firstReadable = table.columns.find(
    (column) => !column.hidden && !column.autoGenerated && !column.readOnly
  );

  if (firstReadable) {
    return formatColumnValue(firstReadable, row[firstReadable.name], lookups);
  }

  return `${table.label} row`;
}

function formatColumnValue(
  column: ColumnMeta,
  value: unknown,
  lookups: LookupCache
): string {
  if (column.foreignKey) {
    const options = lookups[column.foreignKey.referencesTable] ?? [];
    const match = options.find((option) => option.value === String(value ?? ""));
    if (match) {
      return match.label;
    }
  }

  if (value === undefined || value === null || value === "") {
    return "—";
  }

  if (column.kind === "boolean") {
    return value ? "Yes" : "No";
  }

  if (column.kind === "date" || column.kind === "timestamp") {
    const date = new Date(String(value));
    if (!Number.isNaN(date.getTime())) {
      return date.toLocaleString();
    }
  }

  return formatCellValue(value);
}

function formatCellValue(value: unknown): string {
  if (value === undefined || value === null || value === "") {
    return "—";
  }

  if (typeof value === "object") {
    return JSON.stringify(value);
  }

  return String(value);
}

function createRowKey(table: TableMeta, row: RowRecord, index: number) {
  const key = table.primaryKeys.map((column) => String(row[column] ?? "")).join("|");
  return key || `${table.name}-${index}`;
}

async function api<T>(accessToken: string, url: string, init?: RequestInit): Promise<T> {
  const headers = new Headers(init?.headers);
  headers.set("Authorization", `Bearer ${accessToken}`);

  const response = await fetch(url, {
    ...init,
    headers
  });

  if (response.status === 204) {
    return undefined as T;
  }

  const data = (await response.json()) as T & { error?: string };

  if (!response.ok) {
    throw new Error(data.error ?? "Request failed.");
  }

  return data;
}

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : "Unknown error";
}

function toDateTimeLocalValue(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return "";
  }

  const pad = (part: number) => String(part).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(
    date.getHours()
  )}:${pad(date.getMinutes())}`;
}
